import type { Metadata } from "next";
import "@/style/css/globals.css";
import HeaderHome from "@/components/common/header-home";
import { geistMono, geistSans } from "@/style/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-primary-background text-primary`}
      >
        <HeaderHome />
        <div className="mt-[64px]">
        {children}
        </div>
      </body>
    </html>
  );
}
